[project]
name = "crewai-eq-screener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai-tools>=0.76.0",
    "langchain-community>=0.4",
    "notebook>=7.4.7",
    "yfinance>=0.2.66",
]
